apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: example
  namespace: example
  annotations:
    avp.kubernetes.io/path: vaults/swexvhvscs2hcf57oxi72v44ae/items/j56gd66gnhzspln2f6y5aio7ra
stringData:
  EXAMPLE: <EXAMPLE>
