apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: avp-helm
          envFrom:
            - secretRef:
                # The vault config created by us
                # See https://argocd-vault-plugin.readthedocs.io/en/stable/config/#kubernetes-secret
                name: argocd-vault-plugin

        - name: avp-kustomize
          envFrom:
            - secretRef:
                name: argocd-vault-plugin

        - name: avp
          envFrom:
            - secretRef:
                name: argocd-vault-plugin
