apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.4.7

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.7/manifests/install.yaml
  - cmp-plugin.yaml

patchesStrategicMerge:
  - argocd-repo-server.yaml
