apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.4.7

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.7/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.12.0/manifests/cmp-sidecar/cmp-plugin.yaml

patchesStrategicMerge:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.12.0/manifests/cmp-sidecar/argocd-repo-server.yaml
  - argocd-repo-server-patch.yaml
